'use client'

import React from 'react'
import { motion } from 'framer-motion'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Info, ArrowRight, Activity, Zap, Wind } from 'lucide-react'
import { MeteorologicalExplanation } from '@/types/weather'

interface ExplainableWeatherProps {
  explanation: MeteorologicalExplanation
}

export function ExplainableWeather({ explanation }: ExplainableWeatherProps) {
  return (
    <Card className="glass-card border-none rounded-[2rem] overflow-hidden shadow-xl">
      <CardHeader className="p-6 pb-0">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 bg-primary/20 rounded-lg">
            <Info className="w-5 h-5 text-primary" />
          </div>
          <CardTitle className="text-xs font-black uppercase tracking-[0.3em] text-white/40">Atmospheric Logic Engine</CardTitle>
        </div>
        <h2 className="text-2xl md:text-3xl font-black italic tracking-tighter uppercase text-white break-words">{explanation.headline}</h2>
      </CardHeader>
      
      <CardContent className="p-6 space-y-4">
        <p className="text-base md:text-lg font-medium text-white/70 leading-relaxed break-words">
          {explanation.reasoning}
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-white/5">
          <motion.div 
            whileHover={{ x: 5 }}
            className="p-4 bg-white/5 rounded-2xl border border-white/5 flex flex-col gap-2"
          >
            <div className="flex items-center gap-2 text-primary">
              <Zap className="w-4 h-4" />
              <span className="text-[10px] font-black uppercase tracking-widest">Primary Cause</span>
            </div>
            <p className="text-sm font-bold text-white/90 leading-snug break-words">{explanation.cause_effect.cause}</p>
          </motion.div>

          <motion.div 
            whileHover={{ x: 5 }}
            className="p-4 bg-white/5 rounded-2xl border border-white/5 flex flex-col gap-2"
          >
            <div className="flex items-center gap-2 text-orange-400">
              <Activity className="w-4 h-4" />
              <span className="text-[10px] font-black uppercase tracking-widest">Observed Effect</span>
            </div>
            <p className="text-sm font-bold text-white/90 leading-snug break-words">{explanation.cause_effect.effect}</p>
          </motion.div>
        </div>

        <div className="p-5 bg-gradient-to-r from-primary/10 to-transparent rounded-2xl border-l-[3px] border-primary">
          <p className="text-[11px] font-bold text-white/40 uppercase tracking-[0.2em] leading-relaxed">
            * This analysis is generated by the Sayanacoda Meteorological Engine using real-time pressure, thermal, and moisture vectors.
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
